protein:
    represented_as: node
    namespace: [uniprot, entrez]
    input_label: [uniprot_protein, entrez_protein]
    properties:
        sequence: str
        description: str
        taxon: str
        mass: int

protein isoform:
    is_a: protein
    inherit_properties: true
    represented_as: node
    namespace: uniprot
    input_label: uniprot_isoform
