#==========================================================================================
#=======                   CONFIGURATION FILE FOR MKDOCS MATERIAL                   =======
#==========================================================================================

site_name: BioCypher
site_url: https://biocypher.org # URL where the webpage will be hosted, by default it it localhost

#=======    Theme Settings   =====
theme:
  name: material
  font:
    text: Lato
    code: Roboto Mono
  logo: assets/img/logo-biocypher.png
  favicon: assets/img/favicon_biocypher_32px.png
  features:
    - content.code.copy
    - content.action.edit
    - navigation.tabs
    - navigation.instant
    - navigation.footer

  palette:
    - scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode

#=======    Website Navigation settings   =====
nav:
  - Home: index.md

  - About:
      - Project: biocypher-project/project.md
      - Design philosophy: biocypher-project/design-philosophy.md
      - Use Cases: biocypher-project/use-cases.md
      - BioCypher + LLMs: biocypher-project/biochatter-integration.md
      - R and Bioconductor: biocypher-project/r-bioc.md

  - Get Started:
      - Installation: installation.md
      - Quickstart: learn/quickstart.md
      - LLM Integration: llms.md

  - Learn:
      - Overview: learn/index.md
      - Tutorials:
          - Overview: learn/tutorials/index.md
          - Python UI track:
              - Hands-on Protein Graphs with BioCypher and Neo4j (Beginner): learn/tutorials/tutorial_basics_neo4j_offline/tutorial_004_neo4j_offline.md
              - Handling complex graph operations (Advanced): learn/tutorials/tutorial002_handling_ontologies.md
              - Data harmonization and merging (Advanced): learn/tutorials/tutorial002_handling_ontologies.md
          - LLM-assisted UI track:
              - Agent API (Beginner): learn/tutorials/agent_api_guide.md
          - OntoWeaver track:
              - OntoWeaver Tutorial (Beginner): learn/tutorials/tutorial_ontoweaver/tutorial_ontoweaver.md

      - HowTo / FAQ:
          - Overview: learn/guides/index.md
          - Standalone Docker Image: learn/guides/htg001_standalone_docker_biocypher.md

      - Explanations:
          - Overview: learn/explanation/index.md
          - Knowledge Graphs: learn/explanation/basics-knowledge-graphs.md
          - Ontologies: learn/explanation/ontologies.md
          - Knowledge Graphs in BioCypher: learn/explanation/knowledge-graph-biocypher.md
          - Adapters: learn/explanation/adapters.md
          - Schema Configuration Philosophy: learn/explanation/schema-config-philosophy.md
          - Graph Class Guide: learn/explanation/graph_class_guide.md
          - Architecture Migration Guide: learn/explanation/architecture-migration.md

  - Reference:
      - Reference Index: reference/index.md
      - API Documentation:
          - reference/source/index.md
          - BioCypher: reference/source/biocypher.md
          - BioCypherWorkflow: reference/source/biocypher-workflow.md
          - Graph Class: reference/source/graph-class.md
          - Output Writing: reference/source/output-write.md
          - Output In-Memory: reference/source/output-in-memory.md
          - Output Driver: reference/source/output-driver.md
          - Download and Cache: reference/source/download-cache.md
          - Ontology Handling: reference/source/ontology.md
          - Graph Handling: reference/source/graph-handling.md
          - Mapping and Translation: reference/source/translation.md
          - Logging: reference/source/logging.md
          - Miscellaneous Utility Functions: reference/source/utils.md
      - BioCypher Configuration: reference/biocypher-config.md
      - Output Configuration:
          - Overview: reference/outputs/index.md
          - Neo4j: reference/outputs/neo4j-output.md
          - SQLite: reference/outputs/sqlite-output.md
          - PostgreSQL: reference/outputs/postgresql-output.md
          - NetworkX: reference/outputs/networkx-output.md
          - Tabular Format: reference/outputs/tabular-output.md
          - RDF: reference/outputs/rdf-output.md
          - OWL: reference/outputs/owl-output.md
          - ArangoDB: reference/outputs/arangodb-output.md
      - Schema Configuration: reference/schema-config.md

  - Community:
      - Join Us: community/index.md
      - Where to Start: community/contribute.md
      - Contribute to the Documentation: community/contribute-docs.md
      - Contribute to the Code Base: community/contribute-codebase.md

  - API reference: api.md

#=======    Extension settings (sorted alphabetically)  =====
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  #----- Python Markdown Extensions
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight: # Note: list of Pygments: https://pygments.org/docs/lexers/
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

  #---------------    Configure the title to the Table of Contents
  - toc:
      title: On this page

#=======    Plugins    =====
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            heading_level: 3
            docstring_style: google
  - mkdocs-jupyter
  - mike
  - tags

repo_url: https://github.com/biocypher/biocypher
repo_name: biocypher/biocypher
edit_uri: edit/main/docs/

extra:
  social:
    - icon: simple/zulip
      link: https://biocypher.zulipchat.com/
    - icon: material/contacts
      link: https://saezlab.org/
  status:
    new: Recently added
    old: from Legacy webpage
    under-dev: page under development
    done: page that does not need modifications for now
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

copyright: © Copyright 2021-2026, BioCypher developers.
