name: 🏗️ Add New Component
description: Add a new BioCypher component (input, output, ontology, pipeline) to the overview board.

title: "[Component Name]"
projects: ["biocypher/3"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to add a new component to our board!

#----------------   Component type for BioCypher --------------
  - type: dropdown
    id: type
    attributes:
      label: What is the type of your adapter?
      multiple: false
      description: Can be any of input, output, ontology, or pipeline.
      options:
        - Input
        - Output
        - Ontology
        - Pipeline
    validations:
      required: true

#----------------   Adapter Granularity   --------------
  - type: dropdown
    id: granularity
    attributes:
      label: Adapter Granularity
      multiple: false
      description: Does your adapter connect to one single original resource (primary), or is the resource already a composite of multiple original resources (secondary)?
      options:
        - Primary
        - Secondary
        - NA (e.g., Pipeline)
    validations:
      required: true

#----------------   Adapter Format   --------------
  - type: dropdown
    id: format
    attributes:
      label: Adapter Format
      description: Which format does the adapter ingest or output?
      multiple: false
      options:
        - ArangoDB
        - Flat file(s) such as CSV
        - Neo4j
        - OWL
        - Parquet
        - Python (objects)
        - RDF
        - SQL
        - Some API
        - NA
        - Other (state below)
    validations:
      required: true

#----------------   Adapter Resource Origin   --------------
  - type: textarea
    id: resource-url
    attributes:
      label: Resource URL
      description: Under which URL can the primary resource be found (could be a homepage, GitHub repository, docs, FTP folder, etc)?
      render: shell
    validations:
      required: true

#----------------   Adapter Repository Description   --------------
  - type: textarea
    id: adapter-url
    attributes:
      label: Adapter URL
      description: Where can the adapter code be found?
      render: shell
    validations:
      required: true

#----------------   Adapter Repository Description   --------------
  - type: dropdown
    id: adapter-type
    attributes:
      label: Adapter Type
      description: Is the resource a database or an ontology?
      options:
        - Database
        - Ontology
        - NA (e.g., Pipeline)
    validations:
      required: true

#----------------   Adapter Data Description   --------------
  - type: textarea
    id: data-type
    attributes:
      label: Data Type
      description: What kind of data is subject of the adapter? Can be a single category (Proteomics, Genetics, etc) in the case of primary adapters, or "Mixed" in some secondary adapters.
      render: shell
    validations:
      required: true

#--------------   Code of Conduct   --------------
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/biocypher/biocypher/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true


  - type: markdown
    attributes:
      value: >
        Thank you for your contribution! 🎉 – The BioCypher Team
