name: 📔 Documentation Improvement
description: Report wrong or missing documentation

title: "[DOC]: "
labels:
  - "docs"
  - "triage"
projects: ["biocypher/1"]

body:
#----------------   Location of the documentation --------------
  - type: textarea
    id: location
    attributes:
      label: Location of the documentation
      description: >
        Please provide the location of the documentation, e.g. "biocypher.BioCypher.add_nodes()" or the
        URL of the documentation, e.g.
        "https://biocypher.org/latest/reference/source/biocypher/#biocypher.BioCypher.add_nodes"
      placeholder: https://biocypher.org/latest/reference/source/
    validations:
      required: true

#----------------   Problem Description --------------
  - type: textarea
    id: problem
    attributes:
      label: Documentation problem
      description: >
        Please provide a description of what documentation you believe needs to be fixed/improved
    validations:
      required: true

#----------------   Suggested Fix  --------------
  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested fix for documentation
      description: >
        Please explain the suggested fix and **why** it's better than the existing documentation
    validations:
      required: true

#--------------   Code of Conduct   --------------
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/biocypher/biocypher/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: markdown
    attributes:
      value: >
        Thank you for your contribution! 🎉 – The BioCypher Team
