name: Add New Component
description: Add a new BioCypher component (input, output, ontology, pipeline) to the overview board.
title: "[Component Name]"
projects: ["biocypher/2"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to add a new component to our board!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: type
    attributes:
      label: What is the type of your adapter?
      multiple: false
      description: Can be any of input, output, ontology, or pipeline.
      options:
        - Input
        - Output
        - Ontology
        - Pipeline
    validations:
      required: true
  - type: dropdown
    id: granularity
    attributes:
      label: Adapter Granularity
      multiple: false
      description: Does your adapter connect to one single original resource (primary), or is the resource already a composite of multiple original resources (secondary)?
      options:
        - Primary
        - Secondary
        - NA (e.g., Pipeline)
    validations:
      required: true
  - type: dropdown
    id: format
    attributes:
      label: Adapter Format
      description: Which format does the adapter ingest or output?
      multiple: false
      options:
        - Flat file(s) such as CSV
        - Python (objects)
        - Some API
        - Parquet
        - OWL
        - Neo4j
        - SQL
        - ArangoDB
        - RDF
        - None
        - Other (state below)
      validations:
        required: true
  - type: textarea
    id: resource-url
    attributes:
      label: Resource URL
      description: Under which URL can the primary resource be found (could be a homepage, GitHub repository, docs, FTP folder, etc)?
      render: shell
    validations:
      required: true
  - type: textarea
    id: adapter-url
    attributes:
      label: Adapter URL
      description: Where can the adapter code be found?
      render: shell
    validations:
      required: true
  - type: dropdown
    id: adapter-type
    attributes:
      label: Adapter Type
      description: Is the resource a database or an ontology?
      options:
        - Database
        - Ontology
        - NA (e.g., Pipeline)
    validations:
      required: true
  - type: textarea
    id: data-type
    attributes:
      label: Data Type
      description: What kind of data is subject of the adapter? Can be a single category (Proteomics, Genetics, etc) in the case of primary adapters, or "Mixed" in some secondary adapters.
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/biocypher/biocypher/blob/main/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
