Title: BioCypher graph schema configuration file

# ---
# "Named Things"
# ---

protein:
  represented_as: node
  preferred_id: uniprot
  input_label: protein
  db_collection_name: proteins
  properties:
    name: str
    score: float
    taxon: int
    genes: str[]

microRNA:
  represented_as: node
  preferred_id: mirbase.mature
  input_label: mirna

complex:
  synonym_for: macromolecular complex
  represented_as: node
  preferred_id: complexportal
  input_label: complex

pathway:
  represented_as: node
  preferred_id: [reactome, wikipathways]
  input_label: [reactome, wikipathways]

gene:
  represented_as: node
  preferred_id: hgnc
  input_label: [hgnc, ensg]
  exclude_properties: accession

disease:
  represented_as: node
  preferred_id: doid
  input_label: Disease

side effect:
  is_a: phenotypic feature
  represented_as: node
  preferred_id: sider.effect
  input_label: sider

sequence variant:
  represented_as: node
  preferred_id: [clinically relevant, known, somatic]
  input_label: [Clinically_relevant_variant, Known_variant, Somatic_mutation]
  properties:
    source: str
    original_source: str
    effect: str
    biotype: str

altered gene product level:
  represented_as: node
  input_label: agpl

decreased gene product level:
  represented_as: node
  input_label: agpl_decreased

lethal variant:
  represented_as: node
  input_label: lethal

snRNA sequence:
  is_a: nucleic acid entity
  represented_as: node
  preferred_id: [intact, rnacentral]
  input_label: [intact_snrna, rnacentral_snrna]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
  exclude_properties: sequence

DNA sequence:
  is_a: nucleic acid entity
  represented_as: node
  preferred_id: ensembl
  input_label: dna
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

dsDNA sequence:
  is_a: [DNA sequence, nucleic acid entity]
  inherit_properties: True
  represented_as: node
  preferred_id: [intact, uniparc]
  input_label: [intact_dsdna, uniprot_archive_dsdna]

# ---
# Associations
# ---

post translational interaction:
  is_a: pairwise molecular interaction
  represented_as: node
  label_as_edge: INTERACTS_POST_TRANSLATIONAL
  input_label: post_translational

phosphorylation:
  is_a: post translational interaction
  represented_as: edge
  input_label: phosphorylation

gene to disease association:
  represented_as: edge
  label_as_edge: PERTURBED_IN_DISEASE
  input_label: [protein_disease, gene_disease]
  exclude_properties: accession

mutation to tissue association:
  is_a: [genotype to tissue association, entity to tissue association, association]
  represented_as: edge
  label_as_edge: Is_Mutated_In
  input_label: Gene_Is_Mutated_In_Cell_Tissue

variant to gene association: # -> Known.... and Somatic....
  represented_as: edge
  source: [known.sequence variant, somatic.sequence variant]
  target: gene
  input_label: [
    VARIANT_FOUND_IN_GENE_Known_variant_Gene,
    VARIANT_FOUND_IN_GENE_Somatic_mutation_Gene
  ]

gene to gene association:
  represented_as: edge
  input_label: gene_gene
  properties:
    directional: bool
    curated: bool
    score: float

gene to variant association:
  is_a: gene to variant association
  represented_as: edge
  input_label: gene_variant
