name: 'Test coverage'
description: 'Check test coverage'

inputs:
  token:
    description: 'A Github PAT'
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate coverage report
      run: uv run coverage run -m pytest --password=your_password_here
      shell: bash
    - name: Generate coverage badge
      run: uv run coverage-badge -f -o docs/coverage/coverage.svg
      shell: bash
    - name: Commit changes
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: coverage
        FOLDER: docs/coverage
        GITHUB_TOKEN: ${{ inputs.token }}
