"""MkDocs hooks for generating the tutorial catalog."""

from __future__ import annotations

import re

from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any

import yaml

if TYPE_CHECKING:
    from mkdocs.config.defaults import MkDocsConfig

LEVELS: tuple[str, ...] = ("beginner", "intermediate", "advanced")
DOCS_ROOT = Path("docs")
TUTORIAL_ROOT = DOCS_ROOT / "learn" / "tutorials"
TUTORIAL_CATALOG_PATH = TUTORIAL_ROOT / "catalog.md"
EXCLUDED_FILES = {"index.md", "catalog.md"}
IGNORED_TAGS = {"legacy"}


@dataclass(frozen=True, slots=True)
class TutorialEntry:
    """Metadata for a tutorial entry in the generated catalog."""

    title: str
    focus: str
    level: str
    relative_path: str


def parse_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    """Extract YAML frontmatter and the Markdown body from a document."""
    match = re.match(r"^---\n(.*?)\n---\n?", text, re.DOTALL)
    if not match:
        return {}, text

    metadata = yaml.safe_load(match.group(1)) or {}
    return metadata, text[match.end() :]


def extract_title(body: str, fallback: str) -> str:
    """Extract the first top-level heading from a Markdown document."""
    match = re.search(r"^#\s+(.+)$", body, re.MULTILINE)
    return match.group(1).strip() if match else fallback


def extract_summary(body: str) -> str:
    """Extract a concise summary from a Markdown document body."""
    match = re.search(r"\*\*What you will do:\*\*\s*(.+)", body)
    if match:
        return match.group(1).strip()

    for block in body.split("\n\n"):
        paragraph = " ".join(line.strip() for line in block.splitlines()).strip()
        if not paragraph:
            continue
        if paragraph.startswith(("#", "<!--")):
            continue
        return paragraph

    return "Documentation page"


def normalise_tags(raw_tags: Any) -> tuple[str, ...]:
    """Return a stable tuple of string tags from frontmatter metadata."""
    if not isinstance(raw_tags, list):
        return ()

    return tuple(tag.strip() for tag in raw_tags if isinstance(tag, str) and tag.strip())


def _find_docs_root(path: Path) -> Path:
    """Find the nearest ``docs`` ancestor for a documentation path."""
    for candidate in (path, *path.parents):
        if candidate.name == "docs":
            return candidate

    return path.parent


def discover_tutorials(tutorial_root: Path) -> dict[str, list[TutorialEntry]]:
    """Collect tagged tutorial pages grouped by level."""
    grouped_tutorials = {level: [] for level in LEVELS}
    tutorial_root = tutorial_root.resolve()
    docs_root = _find_docs_root(tutorial_root).resolve()

    for path in sorted(docs_root.rglob("*.md")):
        if path.name in EXCLUDED_FILES:
            continue

        try:
            relative_to_tutorial_root = path.resolve().relative_to(tutorial_root)
        except ValueError:
            continue

        metadata, body = parse_frontmatter(path.read_text(encoding="utf-8"))
        tags = normalise_tags(metadata.get("tags", []))

        if "tutorial" not in tags:
            continue
        if any(tag in IGNORED_TAGS for tag in tags):
            continue

        level = next((candidate for candidate in LEVELS if candidate in tags), None)
        if level is None:
            continue

        grouped_tutorials[level].append(
            TutorialEntry(
                title=extract_title(body=body, fallback=path.stem),
                focus=extract_summary(body=body).replace("Documentation page", "Tutorial"),
                level=level,
                relative_path=relative_to_tutorial_root.as_posix(),
            ),
        )

    for entries in grouped_tutorials.values():
        entries.sort(key=lambda entry: entry.title.casefold())

    return grouped_tutorials


def render_catalog(grouped_tutorials: dict[str, list[TutorialEntry]]) -> str:
    """Render the tutorial catalog as Markdown."""
    parts = [
        "# Tutorial Catalog",
        "",
        "<!-- This file is generated by docs_hooks.py. Do not edit manually. -->",
        "",
        "Browse all BioCypher tutorials by difficulty level.",
        "",
        "Only tutorials tagged with both `tutorial` and a difficulty level are included here.",
        "",
    ]

    for level in LEVELS:
        parts.extend(
            [
                f"## {level.capitalize()}",
                "",
                "| Tutorial | Focus | Link |",
                "| --- | --- | --- |",
            ],
        )

        entries = grouped_tutorials[level]
        if entries:
            parts.extend(
                [f"| {entry.title} | {entry.focus} | [Open tutorial]({entry.relative_path}) |" for entry in entries],
            )
        else:
            parts.append("| No tutorials yet | - | - |")

        parts.append("")

    return "\n".join(parts)


def write_tutorial_catalog(
    tutorial_root: Path = TUTORIAL_ROOT,
    catalog_path: Path = TUTORIAL_CATALOG_PATH,
) -> None:
    """Generate the tutorial catalog page from tagged tutorials."""
    grouped_tutorials = discover_tutorials(tutorial_root=tutorial_root)
    catalog_path.write_text(render_catalog(grouped_tutorials), encoding="utf-8")


def on_pre_build(config: MkDocsConfig) -> None:
    """Generate the tutorial catalog before MkDocs builds pages."""
    del config
    write_tutorial_catalog()
