name: 'Build docs'
description: 'Build docs and run doc tests'

runs:
  using: "composite"
  steps:
    - name: Test code snippets in documentation
      run: uv run make doctest --directory docs/
      shell: bash
    - name: Build documentation
      run: uv run make html --directory docs/
      shell: bash
