name: docs_ci
on:
  push:
    branches:
      - master
      - main
      - gh-mkdocs-migration
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    #----------------------------------------------
    #  checkout repo and set-up python and poetry
    #----------------------------------------------
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Setup Python and Poetry
      uses: ./.github/actions/setup
    #----------------------------------------------
    #            install dependencies
    #----------------------------------------------
    - name: Install dependencies
      uses: ./.github/actions/install
    #----------------------------------------------
    #            deploy web page
    #----------------------------------------------
    - uses: actions/checkout@v4
    - name: Configure Git Credentials
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
    - uses: actions/cache@v4
      with:
        key: mkdocs-material-${{ env.cache_id }}
        path: .cache
        restore-keys: |
          mkdocs-material-
    - run: poetry run mkdocs gh-deploy --remote-branch gh-mkdocs-migration --force
