name: Docs (TEMPORARILY DISABLED)

# DISABLED: This workflow is temporarily disabled during transition to a new docs build system
# Original trigger configuration:
# on:
#   pull_request:
#   push:
#     branches:
#       - main

# Temporarily disable all triggers
on:
  # Empty workflow_dispatch allows manual triggering if needed, but prevents automatic runs
  workflow_dispatch:

jobs:
  build_docs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    #----------------------------------------------
    # check-out repo and set-up python and poetry
    #----------------------------------------------
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Setup Python and Poetry
      uses: ./.github/actions/setup
    #----------------------------------------------
    #            install dependencies
    #----------------------------------------------
    - name: Install dependencies
      uses: ./.github/actions/install
    - name: Install pandoc
      run: sudo apt-get -y install pandoc
    #----------------------------------------------
    #                  build docs
    #----------------------------------------------
    - name: Build docs
      uses: ./.github/actions/build_docs

  build_and_deploy_docs:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    #----------------------------------------------
    # check-out repo and set-up python and poetry
    #----------------------------------------------
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Setup Python and Poetry
      uses: ./.github/actions/setup
    #----------------------------------------------
    #            install dependencies
    #----------------------------------------------
    - name: Install dependencies
      uses: ./.github/actions/install
    - name: Install pandoc
      run: sudo apt-get -y install pandoc
    #----------------------------------------------
    #                  build docs
    #----------------------------------------------
    - name: Install dependencies
      uses: ./.github/actions/build_docs
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        touch docs/_build/html/.nojekyll
        echo 'biocypher.org' > docs/_build/html/CNAME
        git add -f docs/_build/
        git commit -m "Update autodoc" -a
    #----------------------------------------------
    #                  deploy docs
    #----------------------------------------------
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: docs/_build/html
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
