name: Tests and code quality checks for pull requests

on: [pull_request]

jobs:
  tests_and_code_quality:
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "macos-13", "windows-latest"]
        python-version: ["3.10", "3.11", "3.12"]
        neo4j-version: ["4.4-enterprise", "5.17.0-enterprise"]
        exclude:
          # Windows tests don't use the PostgreSQL/Neo4j Docker containers
          - os: "windows-latest"
            neo4j-version: "4.4-enterprise"
          # https://github.com/biocypher/biocypher/issues/339
          - os: "macos-latest"
            neo4j-version: "4.4-enterprise"
    runs-on: ${{ matrix.os }}
    env:
      POETRY_VERSION: 1.5.1
    defaults:
      run:
        shell: bash

    steps:
    #----------------------------------------------
    #  checkout repo and set-up python and poetry
    #----------------------------------------------
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Setup Python and Poetry
      uses: ./.github/actions/setup
      with:
        PYTHON_VERSION: ${{ matrix.python-version }}
        POETRY_VERSION: ${{ env.POETRY_VERSION }}
    #----------------------------------------------
    #       install dependencies
    #----------------------------------------------
    - name: Install dependencies
      uses: ./.github/actions/install
      with:
        PYTHON_VERSION: ${{ matrix.python-version }}

    #----------------------------------------------
    #      run tests and code quality checks
    #----------------------------------------------
    - name: Run tests
      uses: ./.github/actions/test
      with:
        NEO4J_VERSION: ${{ matrix.neo4j-version }}
